name: Build AppImage
on:
  workflow_dispatch:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "main"

jobs:
  version:
    name: Postman AppImage
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install libfuse2
        run: sudo apt-get install -y libfuse2      
      - name: Build
        id: build
        uses: valicm/appimage-bash@main
        with:
          version_url: 'https://dl.pstmn.io/download/latest/linux64'
          version_file: 'app/resources/app/package.json'
          version_bash: 'jq -r  .version'
          version_icon: 'icon_128x128.png'
      - name: Upload artifact
        if: ${{ env.APP_UPDATE_NEEDED == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_SHORT_NAME }}.AppImage
          path: 'dist'
      - name: Release
        if: ${{ env.APP_UPDATE_NEEDED == 'true' }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ env.APP_NAME }} AppImage ${{ env.APP_VERSION }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            dist/
          repo_token: ${{ secrets.GITHUB_TOKEN }}
